name: sane_uuid
description: >
  A sane UUID implementation with support for generating v1, v4 and v5 UUIDs according to RFC4122.
  Comes with a versatile UUID type with support for any syntactically valid UUID, allowing comparison/sorting,
  equality checks and access to the fields defined by RFC4122, including the UUID version.
version: 1.0.0-alpha.2
homepage: https://github.com/BjoernPetersen/sane_uuid

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Static analysis
  meta: ^1.3.0

  # Hashing functions for v5 UUIDs
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.14.4

  # Static analysis
  lint: ^1.5.0
