name: sane_uuid
description: A sane UUID implementation.
version: 0.1.0-alpha.1
homepage: https://github.com/BjoernPetersen/sane_uuid

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # Static analysis
  meta: ^1.3.0

  # Hashing functions for v5 UUIDs
  crypto: ^3.0.0

dev_dependencies:
  test: ^1.14.4

  # Static analysis
  lint: ^1.5.0
